### PR TITLE
28 iterative deepening

### LINKED ISSUE #28: Use iterative deepening

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #28

---
This change is [Reviewable](https://reviewable.io/reviews/shanek21/connect-four-ai/29)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r1.
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/29)*

**Comment by williamalu** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/29)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r2.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/29)*

**Comment by williamalu** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/29)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/29)*

**Pull request merged**
