### PR TITLE
11: add testing framework

### LINKED ISSUE #11: Set up testing framework

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #11

---
This change is [Reviewable](https://reviewable.io/reviews/shanek21/connect-four-ai/12)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 7 of 10 files at r1.
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[.gitignore, line 10 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-msaun7yJDWuYIDk5p:-L-msaun7yJDWuYIDk5q:b-r0bsan) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/.gitignore#L10)):*
> ```
> test_exec
> 
> *.o
> ```

Can you add a comment about object files?

---

*[Makefile, line 18 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-mtq0dUzptFX_ID8LM:-L-mtq0dUzptFX_ID8LN:b3a4812) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/Makefile#L18)):*
> ```Makefile
> 
> # Compile and link connect_four.cpp to connect_four, using our compiler and
> #   and flags
> ```

Sorry I just noticed this. `and` is there twice

---

*[scripts/lint.sh, line 9 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-mtB8JV94WGYAlZHXW:-L-mtB8JV94WGYAlZHXX:b-hject6) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/scripts/lint.sh#L9)):*
> ```Shell
> echo Running cppcheck...
> # cppcheck doesn't know about built in c++ libraries, this supresses warnings
> cppcheck --enable=all --suppress='*:lib/*' src/ include/ test/
> ```

Why does lib have asterisks and stuff?

---

*[test/test.cpp, line 2 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-mtHNJHIjE_OoF0mpn:-L-mtHNJHIjE_OoF0mpo:b2p5jdq) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/test/test.cpp#L2)):*
> ```cpp
> // This tells Catch to provide a main() - only do this in one cpp file
> #include "../lib/catch.hpp"  // cppcheck-suppress
> ```

Why the suppress?

---

*[test/test_main.cpp, line 2 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-mtT9JFUauvjX6JKcl:-L-mtT9JFUauvjX6JKcm:btcc0ao) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/test/test_main.cpp#L2)):*
> ```cpp
> #define CATCH_CONFIG_MAIN
> #include "../lib/catch.hpp"  // cppcheck-suppress
> ```

What is this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12)*

**Comment by davidabrahams** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[.gitignore, line 10 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-msaun7yJDWuYIDk5p:-L-oAENoSEynRgDesJN3:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/.gitignore#L10)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you add a comment about object files?
</blockquote></details>

Done.

---

*[Makefile, line 18 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-mtq0dUzptFX_ID8LM:-L-oAF8yJ3i15mbC7RWr:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/Makefile#L18)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Sorry I just noticed this. `and` is there twice
</blockquote></details>

Done.

---

*[scripts/lint.sh, line 9 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-mtB8JV94WGYAlZHXW:-L-ncnnXsYjUUqkGWgkh:bvgsckp) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/scripts/lint.sh#L9)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Why does lib have asterisks and stuff?
</blockquote></details>

Trying to not lint lib/. Removed.

---

*[test/test.cpp, line 2 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-mtHNJHIjE_OoF0mpn:-L-oA-fSYwj47n3ra47d:b-l2c8h6) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/test/test.cpp#L2)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Why the suppress?
</blockquote></details>

Another way i tried to not lint lib. Didnt work.

---

*[test/test_main.cpp, line 2 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12#-L-mtT9JFUauvjX6JKcl:-L-oA22KOe8i3ZoRiwtF:bu6ly6b) ([raw file](https://github.com/shanek21/connect-four-ai/blob/d1f676aadf98b5bced3e3d7c4e62f7acca101c06/test/test_main.cpp#L2)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

What is this file?
</blockquote></details>

I think explained in person?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12)*

**Comment by williamalu** [comment]
Reviewed 1 of 6 files at r2.
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12)*

**Comment by williamalu** [comment]
Reviewed 3 of 10 files at r1, 1 of 6 files at r2.
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12)*

**Comment by williamalu** [comment]
Reviewed 1 of 10 files at r1, 3 of 6 files at r2.
Review status: 2 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12)*

**Comment by williamalu** [comment]
Reviewed 1 of 1 files at r3.
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12)*

**Comment by shanek21** [comment]
Reviewed 2 of 10 files at r1, 5 of 6 files at r2, 1 of 1 files at r4.
Review status: 3 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r5.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12)*

**Comment by williamalu** [comment]
Reviewed 1 of 1 files at r5.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/12)*

**Pull request merged**
