### PR TITLE
25 position cache

### LINKED ISSUE #25: cache positions we've seen before

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #25

---
This change is [Reviewable](https://reviewable.io/reviews/shanek21/connect-four-ai/27)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 8 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[Makefile, line 56 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0Bi3a4MzXgX3XeRZtU:-L0BpZqMK7n7FJ4Q4auc:bws7bal) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/Makefile#L56)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

@shanek21 so, we have the state and table objects being compiled into the solver test executable, because the solver has references to State and Table. Is this the best way to do this? It feels like we should be able to compile state.o and table.o into solver.o, and then just use that.
</blockquote></details>

I'm not sure. If just using solver.o doesn't work, then I would guess this is the next best solution.

---

*[include/table.h, line 14 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BqxKZNG5H7xLreUmE:-L0BqxKZNG5H7xLreUmF:blq31g2) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/include/table.h#L14)):*
> ```objc
>   explicit Table(uint32_t numBits);
>   void put(uint64_t boardKey, int8_t score);
>   int8_t get(uint64_t boardKey);
> ```

newline after public stuff

---

*[src/solver.cpp, line 5 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BsmebeCyj8jMqrgih:-L0BsmebeCyj8jMqrgii:b-lypkxx) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/solver.cpp#L5)):*
> ```cpp
> #include <iostream>
> #include "../include/solver.h"
> ```

Hahahahaha love it

---

*[src/solver.cpp, line 6 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BsTBgc9KuOvaP43B1:-L0BsTBgc9KuOvaP43B2:b-ooave3) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/solver.cpp#L6)):*
> ```cpp
> #include "../include/solver.h"
> 
> Solver::Solver() : table(67108744) {  // use ~64 MB of data
> ```

Is there maybe a cleaner/more readable way to do this? Maybe get the sizeof your Entry struct and multiply it by some number? Having a really long hardcoded value just seems kinda odd.

---

*[src/state.cpp, line 46 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BqdcV2CculP0IEjkJ:-L0BqdcWSfRIIzJQVUT3:bef55q5) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/state.cpp#L46)):*
> ```cpp
> uint64_t State::boardKey() const {
>   // TODO(davidabrahams): I'm not entirely sure how this makes each potential
>   //   gamestate have a unique key
> ```

What needs to happen to resolve this TODO?

---

*[src/table.cpp, line 8 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BrRTxjCMvniZb1KDq:-L0BrRTxjCMvniZb1KDr:b-6nzv6e) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/table.cpp#L8)):*
> ```cpp
> Table::Table(uint32_t numBits) {
>   int entryMem = sizeof(Entry);
>   // TODO(davidabrahams) remove this
> ```

Remove this?

---

*[src/table.cpp, line 11 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BrYQPNYfMSjWFtP2c:-L0BrYQQV41P7ghdu4Gm:b-54egmn) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/table.cpp#L11)):*
> ```cpp
>   assert(entryMem == 8);  // should be 8 bytes
>   int storedBoards = numBits / sizeof(Entry);
>   /* std::cout << storedBoards << std::endl; */
> ```

Delete this?

---

*[test/solver.cpp, line 20 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BsGiy0enuZCc6-KpR:-L0BsGiy0enuZCc6-KpS:b-kzw4ar) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/test/solver.cpp#L20)):*
> ```cpp
>     S = State::boardFromNums("326615663752621323655335514271");
>     REQUIRE(solver.negamax(S) > 0);
>     S = State::boardFromNums("24617524315172127");
> ```

Sweet! How long does this take now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Makefile, line 56 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0Bi3a4MzXgX3XeRZtU:-L0C684myQyznfBLKq7T:b-nucc70) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/Makefile#L56)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I'm not sure. If just using solver.o doesn't work, then I would guess this is the next best solution.
</blockquote></details>

I will ask Hieu.

---

*[include/table.h, line 14 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BqxKZNG5H7xLreUmE:-L0C5PlXIIhIzMRnXzim:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/include/table.h#L14)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

newline after public stuff
</blockquote></details>

Done.

---

*[src/solver.cpp, line 6 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BsTBgc9KuOvaP43B1:-L0C5GOC0nsj2qbpcJIB:b-q2rq4g) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/solver.cpp#L6)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Is there maybe a cleaner/more readable way to do this? Maybe get the sizeof your Entry struct and multiply it by some number? Having a really long hardcoded value just seems kinda odd.
</blockquote></details>

Depends what you want the constructor input to be. It could be a number of board positions, or an amount of memory. I'm fine with either

---

*[src/state.cpp, line 46 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BqdcV2CculP0IEjkJ:-L0C5U5FJJf_bjki4hPN:b-blcfhw) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/state.cpp#L46)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

What needs to happen to resolve this TODO?
</blockquote></details>

Uh, either someone could figure it out and tell me, or I'll go back to it if I have time and try to figure it out (I got this idea from someone else, but I didn't confirm their logic. I did want to understand it for the sake of learning, so I left the TODO)

---

*[src/table.cpp, line 8 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BrRTxjCMvniZb1KDq:-L0C5kHhCGjk7Iox7ue2:b-eu7doy) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/table.cpp#L8)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Remove this?
</blockquote></details>

Oh thats targetted at the assert. Actually imma leave it in

---

*[src/table.cpp, line 11 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BrYQPNYfMSjWFtP2c:-L0C5q5r-uE3flfMWaaP:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/table.cpp#L11)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Delete this?
</blockquote></details>

Done.

---

*[test/solver.cpp, line 20 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BsGiy0enuZCc6-KpR:-L0C5wdoaBUaKD7uorAE:baquxk2) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/test/solver.cpp#L20)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Sweet! How long does this take now?
</blockquote></details>

```
➜  connect-four-ai git:(25-position-cache) time make test
mkdir -p obj
g++  -g -std=c++11 -Wall src/table.cpp -c -o obj/table.o
g++  -g -std=c++11 -Wall src/solver.cpp -c -o obj/solver.o
g++  -g -std=c++11 -Wall obj/test_main.o test/solver.cpp obj/solver.o obj/state.o obj/table.o -o test/solver
./test/state
===============================================================================
All tests passed (50 assertions in 6 test cases)

./test/solver
===============================================================================
All tests passed (10 assertions in 1 test case)

make test  1.38s user 0.06s system 97% cpu 1.476 total

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r2.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/solver.cpp, line 6 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BsTBgc9KuOvaP43B1:-L0CY2nGclSGQJHR0jAt:bijnjv0) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/solver.cpp#L6)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Depends what you want the constructor input to be. It could be a number of board positions, or an amount of memory. I'm fine with either
</blockquote></details>

I like number of board positions I think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r3.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by williamalu** [comment]
Reviewed 5 of 8 files at r1, 1 of 2 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by williamalu** [comment]
Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by williamalu** [comment]
Reviewed 2 of 6 files at r4.
Review status: 4 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by williamalu** [comment]
Reviewed 1 of 6 files at r4.
Review status: 5 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/table.cpp, line 8 at r5](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0FxffcoLDKMhtfPm6I:-L0FxffcoLDKMhtfPm6J:bpc24gs) ([raw file](https://github.com/shanek21/connect-four-ai/blob/509ba0305323073c7d38a4c1f0b9d49a055cc37c/src/table.cpp#L8)):*
> ```cpp
> Table::Table(uint32_t numBits) {
>   int entryMem = sizeof(Entry);
>   assert(entryMem == 8);  // should be 8 bytes
> ```

Shouldn't this be 9 bytes? Your struct contains a 64 bit unsigned integer and an 8 bit signed integer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by williamalu** [comment]
Review status: 6 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/solver.cpp, line 6 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BsTBgc9KuOvaP43B1:-L0HuoznALTD3dTtmJyC:b-t4p88j) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/solver.cpp#L6)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I like number of board positions I think
</blockquote></details>

Doesn't matter to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by shanek21** [comment]
Reviewed 2 of 8 files at r1, 5 of 6 files at r4, 1 of 1 files at r6.
Review status: 6 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by williamalu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/table.cpp, line 8 at r5](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0FxffcoLDKMhtfPm6I:-L0HvJVYMhSH1mrdJ7Dp:b95qg7o) ([raw file](https://github.com/shanek21/connect-four-ai/blob/509ba0305323073c7d38a4c1f0b9d49a055cc37c/src/table.cpp#L8)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

Shouldn't this be 9 bytes? Your struct contains a 64 bit unsigned integer and an 8 bit signed integer.
</blockquote></details>

Nevermind, read about the syntax of ```uint64_t board: 56;```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 6 files at r4.
Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/solver.cpp, line 6 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27#-L0BsTBgc9KuOvaP43B1:-L0HvfYwK2DHtfK6dIPG:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/8fe5a4d9253cbb2fc42a11a3828b876e096042e6/src/solver.cpp#L6)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

Doesn't matter to me.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r7.
Review status: 7 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Comment by williamalu** [comment]
Reviewed 1 of 6 files at r4, 1 of 1 files at r6, 3 of 3 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/27)*

**Pull request merged**
