### PR TITLE
1: added board renderer

### LINKED ISSUE #1: Create visual representation of Connect Four board
Not an intelligent rendering of an existing board - just hard-coding a board rendering. Trying to get a good understanding of `ncurses` library.

### PR DESCRIPTION
**Pull request by williamalu**
Closes #1

---
This change is [Reviewable](https://reviewable.io/reviews/shanek21/connect-four-ai/22)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main.cpp, line 7 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22#-L078k2MC3Gh7C6n8tKo:-L078k2MC3Gh7C6n8tKp:byt7gd3) ([raw file](https://github.com/shanek21/connect-four-ai/blob/b41654bbb21090646be4174677dcef22b90879d0/src/main.cpp#L7)):*
> ```cpp
> 
> int main() {
>   setUpScreen();
> ```

setup is one word, so I think it shouldn't be camel cased.

---

*[src/renderer.cpp, line 36 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22#-L078_eL2qDMVXA9bw6F:-L078_eL2qDMVXA9bw6G:b-uz803i) ([raw file](https://github.com/shanek21/connect-four-ai/blob/b41654bbb21090646be4174677dcef22b90879d0/src/renderer.cpp#L36)):*
> ```cpp
>   noecho();
>   init_pair(1, COLOR_RED, COLOR_WHITE);     // Creates red tiles
>   init_pair(2, COLOR_BLACK, COLOR_WHITE);   // Creates yellow tiles
> ```

Code says black, comment says yellow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[Makefile, line 17 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22#-L07pbaYiuupSzgetcmH:-L07pbaYiuupSzgetcmI:b-iufcry) ([raw file](https://github.com/shanek21/connect-four-ai/blob/b41654bbb21090646be4174677dcef22b90879d0/Makefile#L17)):*
> ```Makefile
> OBJS = $(OBJ_DIR)/main.o \
>       $(OBJ_DIR)/state.o \
> 			$(OBJ_DIR)/renderer.o
> ```

Got some inconsistent indentation here. Also, the previous line doesn't have a \t, I think

---

*[src/renderer.cpp, line 4 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22#-L07q0F6a4WSBxHyV7jw:-L07q0F6a4WSBxHyV7jx:b-mtysc5) ([raw file](https://github.com/shanek21/connect-four-ai/blob/b41654bbb21090646be4174677dcef22b90879d0/src/renderer.cpp#L4)):*
> ```cpp
> 
> 
> int tileOffsets[7] = {2, 6, 10, 14, 18, 22, 26};
> ```

Should be able to define this dynamically based on width of State (in case we make a wider connect-4 board)

---

*[src/renderer.cpp, line 37 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22#-L07pvG3jibP2LUGMM-z:-L07pvG3jibP2LUGMM0-:b-gr5ckm) ([raw file](https://github.com/shanek21/connect-four-ai/blob/b41654bbb21090646be4174677dcef22b90879d0/src/renderer.cpp#L37)):*
> ```cpp
>   init_pair(1, COLOR_RED, COLOR_WHITE);     // Creates red tiles
>   init_pair(2, COLOR_BLACK, COLOR_WHITE);   // Creates yellow tiles
>   init_pair(3, 244, COLOR_WHITE);
> ```

Perhaps comment which color 244 is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22)*

**Comment by davidabrahams** [comment]
Issue # in commit message please

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/renderer.cpp, line 36 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22#-L078_eL2qDMVXA9bw6F:-L07rCW2ASRMfXay__hR:b6qtq3n) ([raw file](https://github.com/shanek21/connect-four-ai/blob/b41654bbb21090646be4174677dcef22b90879d0/src/renderer.cpp#L36)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Code says black, comment says yellow
</blockquote></details>

https://youtu.be/UePtoxDhJSw

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22#-:-L07r3sI73ZfTtB8VqoX:b-9e9ld2)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r2.
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/22)*

**Pull request merged**
