### PR TITLE
19 alpha beta

### LINKED ISSUE #10: Create a test for a brute-force minimax implementation
Success criteria:

instantiate a near-complete board
create a dummy function
test the dummy function

### LINKED ISSUE #19: implement alpha-beta pruning

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #19

---
This change is [Reviewable](https://reviewable.io/reviews/shanek21/connect-four-ai/23)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 5 of 5 files at r1.
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[include/negamax.h, line 1 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AThPYPDf7TNsaCYFE:-L0AThPZKh_Y75kzAil9:bbxa4r1) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/include/negamax.h#L1)):*
> ```objc
> #ifndef INCLUDE_NEGAMAX_H_
> ```

Call this file `solver.h`?

---

*[src/negamax.cpp, line 1 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0ATj_fTm8NaODKZecO:-L0ATj_fTm8NaODKZecP:bndwayw) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/negamax.cpp#L1)):*
> ```cpp
> #include <limits>
> ```

Call this file `solver.cpp`?

---

*[src/negamax.cpp, line 8 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AUyE0Dch9i3cWbc86:-L0AUyE1CLgapR3doLIj:b4ka39) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/negamax.cpp#L8)):*
> ```cpp
> 
> Solver::Solver() {
>   int w = State::WIDTH;
> ```

Can you put all of this into a function and then call the function in this constructor?

---

*[src/negamax.cpp, line 19 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AU8iaTA6WNPjKKTLi:-L0AU8iaTA6WNPjKKTLj:b-7wihvb) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/negamax.cpp#L19)):*
> ```cpp
> }
> 
> int Solver::negamax(State S) {
> ```

Change to lower case `s`?

---

*[src/negamax.cpp, line 24 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AVd1Cq_j0WN7ERBW3:-L0AVd1Cq_j0WN7ERBW4:b-ufkh55) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/negamax.cpp#L24)):*
> ```cpp
> 
> /**
>  * @param S - the current state to evaluate
> ```

Add `@param` for lowerBound and upperBound?

---

*[src/negamax.cpp, line 30 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AV_MRdigFzaYr12GU:-L0AV_MRdigFzaYr12GV:bnimprb) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/negamax.cpp#L30)):*
> ```cpp
>  */
> int Solver::negamax(State S, int lowerBound, int upperBound) {
>   if (S.isBoardFull()) {  // if the game is over, it's a draw
> ```

Move return to inline?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23)*

**Comment by davidabrahams** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[include/solver.h, line 1 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AThPYPDf7TNsaCYFE:-L0AcM-NgdDI7uTM4o1Z:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/include/solver.h#L1)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Call this file `solver.h`?
</blockquote></details>

Done.

---

*[src/solver.cpp, line 8 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AUyE0Dch9i3cWbc86:-L0AcO5k-VbboEnvBfEB:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/solver.cpp#L8)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you put all of this into a function and then call the function in this constructor?
</blockquote></details>

Done.

---

*[src/solver.cpp, line 19 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AU8iaTA6WNPjKKTLi:-L0AcUov8Us5W734iNx7:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/solver.cpp#L19)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Change to lower case `s`?
</blockquote></details>

Done.

---

*[src/solver.cpp, line 24 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AVd1Cq_j0WN7ERBW3:-L0AcfopVY5PX3juRVNj:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/solver.cpp#L24)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Add `@param` for lowerBound and upperBound?
</blockquote></details>

Done.

---

*[src/solver.cpp, line 30 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AV_MRdigFzaYr12GU:-L0AckeMVrrHNHotlmcs:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/solver.cpp#L30)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Move return to inline?
</blockquote></details>

Done.

---

*[src/negamax.cpp, line 1 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0ATj_fTm8NaODKZecO:-L0AbNESbdI3tmfyWUue:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/eb0f723d9ccb523e38ade5f88a7336f71b2fb5be/src/negamax.cpp#L1)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Call this file `solver.cpp`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23)*

**Comment by shanek21** [comment]
Reviewed 8 of 8 files at r3.
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/solver, line 0 at r3](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23#-L0AfAq0Nl983MvXsEzM:-L0AfAq0Nl983MvXsEzN:b-sp5cca) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fe5693a1b65c6d385f8b5c38187e99b90c550dad/test/solver#L0)):*
binary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/23)*

**Pull request closed without merging**
