### PR TITLE
3: make file

### LINKED ISSUE #3: Setup makefile
Potentially decide if we should use cmake

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #3 

Super minimalistic. I've seen a lot of Makefiles dynamically find src files, but I figure for now we can hard-code them into the Makefile, and once we feel the need to do it dynamically, we can update it.

---
This change is [Reviewable](https://reviewable.io/reviews/shanek21/connect-four-ai/9)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 3 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/connect_four.cpp, line 4 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SRh6dwEvHSHdgvPuq:-L-SRh6dwEvHSHdgvPur:b-9hms5m) ([raw file](https://github.com/shanek21/connect-four-ai/blob/0a2e4476d118f4b17db6f9dbca49035e9a01f11c/src/connect_four.cpp#L4)):*
> ```cpp
> 
> int main() {
>   std::cout << "Hello World!";
> ```

tabs are 4 spaces pls :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by davidabrahams** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/connect_four.cpp, line 4 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SRh6dwEvHSHdgvPuq:-L-SRtvJ4Oj2kWnWoxFX:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/0a2e4476d118f4b17db6f9dbca49035e9a01f11c/src/connect_four.cpp#L4)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

tabs are 4 spaces pls :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by shanek21** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/connect_four.cpp, line 4 at r3](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SXxiaatJH_IX2hN_b:-L-SXxiaatJH_IX2hN_c:bwm63cm) ([raw file](https://github.com/shanek21/connect-four-ai/blob/02a41949f4008d67e51330da3fd1688e40da91f7/src/connect_four.cpp#L4)):*
> ```cpp
> 
> int main() {
>     std::cout << "Hello World!";
> ```

Change back to 2 spaces per offline discussion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Reviewed 1 of 2 files at r3.
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[.travis.yml, line 8 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SfVAOA-b9ZlyyXuRc:-L-SfVAOA-b9ZlyyXuRd:b1cwn34) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/.travis.yml#L8)):*
> ```YAML
> 
> script:
> - cpplint src/*.cpp include/*.h
> ```

Apparently you can use a --recursive flag to dynamically build a list of files https://github.com/cpplint/cpplint/issues/33

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Reviewed 2 of 4 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Reviewed 1 of 1 files at r4.
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[Makefile, line 6 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SiGI_iJh7tbR9Q3NP:-L-SiGI_iJh7tbR9Q3NQ:beke0p1) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/Makefile#L6)):*
> ```Makefile
> # This tutorial: http://mrbook.org/blog/tutorials/make/
> 
> CC := g++ # explicitly set the compiler
> ```

Is there a specific reason we're using ```:=``` instead of ```=```? I'm reading about "simply expanded variables," but I don't see how that affects our project specifically. (unless this is just good practice?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/connect_four.cpp, line 4 at r3](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SXxiaatJH_IX2hN_b:-L-Sj3g9WiO9rgxLDrWT:bad4nbr) ([raw file](https://github.com/shanek21/connect-four-ai/blob/02a41949f4008d67e51330da3fd1688e40da91f7/src/connect_four.cpp#L4)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Change back to 2 spaces per offline discussion
</blockquote></details>

Wasn't there for this. What's this style preference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by shanek21** [comment]
Reviewed 1 of 3 files at r5.
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[Makefile, line 6 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SiGI_iJh7tbR9Q3NP:-L-SkcE1U2p3AbnRLTV7:b-4gk1jm) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/Makefile#L6)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

Is there a specific reason we're using ```:=``` instead of ```=```? I'm reading about "simply expanded variables," but I don't see how that affects our project specifically. (unless this is just good practice?)
</blockquote></details>

Good question. I think I normally see `=`. @davidabrahams?

---

*[src/connect_four.cpp, line 4 at r3](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SXxiaatJH_IX2hN_b:-L-Skhy2HN_r2MyLBBqN:buofsnh) ([raw file](https://github.com/shanek21/connect-four-ai/blob/02a41949f4008d67e51330da3fd1688e40da91f7/src/connect_four.cpp#L4)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

Wasn't there for this. What's this style preference?
</blockquote></details>

Google's c++ style guide says 2 spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by davidabrahams** [comment]
Review status: 2 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[.travis.yml, line 8 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SfVAOA-b9ZlyyXuRc:-L-SnNKNQYSFbLm16j8E:b-ndukvs) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/.travis.yml#L8)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

Apparently you can use a --recursive flag to dynamically build a list of files https://github.com/cpplint/cpplint/issues/33
</blockquote></details>

Awesome! Thank you! I integrated this change :)

---

*[Makefile, line 14 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SSOMXxT6XEX2HOoCK:-L-SoCOrgVkqw0ftcvBP:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/0a2e4476d118f4b17db6f9dbca49035e9a01f11c/Makefile#L14)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you capitalize all the non in-line comments?
</blockquote></details>

Done.

---

*[Makefile, line 15 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SSFG3QoFwEPeLtdRk:-L-So44QwF3sw31vRv2P:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/0a2e4476d118f4b17db6f9dbca49035e9a01f11c/Makefile#L15)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Definitely up for discussion, but I like indenting any lines that aren't the first line in a multi-line comment.
</blockquote></details>

Done.

---

*[Makefile, line 6 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SiGI_iJh7tbR9Q3NP:-L-SnphSfpv1Kjbt7WEq:brzirw3) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/Makefile#L6)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Good question. I think I normally see `=`. @davidabrahams?
</blockquote></details>

https://stackoverflow.com/questions/10227598/what-is-the-difference-between-and-in-make-file

TBH I have no idea which one we want. Basically, it looks like if we have some variable (say `Y`) reference `X`, and then reassign `X` later, with `=` `Y` would update, with `:=` it wouldn't. What do you guys think?

---

*[src/connect_four.cpp, line 4 at r3](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SXxiaatJH_IX2hN_b:-L-SoE-qbt0ocM49iukj:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/02a41949f4008d67e51330da3fd1688e40da91f7/src/connect_four.cpp#L4)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Google's c++ style guide says 2 spaces
</blockquote></details>

Done.

---

*[connect_four, line  at r2](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SRt80ZFoSh6l9KeMP:-L-SoFT-NpDFJp5l5hFM:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/86c5c852d38be624960831b536abf2c9405db1a2/connect_four#L)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you add `connect_four` to our `.gitignore`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Reviewed 1 of 2 files at r6.
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 5 at r6](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SofdRQlVA3rchIFqO:-L-SofdRQlVA3rchIFqP:b-b4jb4i) ([raw file](https://github.com/shanek21/connect-four-ai/blob/4cf7c759a7546fb206174c7fbdb42843cb09b1d2/.travis.yml#L5)):*
> ```YAML
> 
> before_install:
> - sudo apt-get -qq update
> ```

You should probably use ```apt``` instead of ```apt-get``` now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by davidabrahams** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 5 at r6](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SofdRQlVA3rchIFqO:-L-Sp2_OmLb6aQK1ishs:bcvecws) ([raw file](https://github.com/shanek21/connect-four-ai/blob/4cf7c759a7546fb206174c7fbdb42843cb09b1d2/.travis.yml#L5)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

You should probably use ```apt``` instead of ```apt-get``` now?
</blockquote></details>

What's the difference? lol FYI, I was basing this on:

https://docs.travis-ci.com/user/installing-dependencies/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[Makefile, line 6 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SiGI_iJh7tbR9Q3NP:-L-SpCV3giFaOb7vDnB0:b9qsfw9) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/Makefile#L6)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

https://stackoverflow.com/questions/10227598/what-is-the-difference-between-and-in-make-file

TBH I have no idea which one we want. Basically, it looks like if we have some variable (say `Y`) reference `X`, and then reassign `X` later, with `=` `Y` would update, with `:=` it wouldn't. What do you guys think?
</blockquote></details>

Gnu has a quick page on this, but it's still unclear which one we should use. https://www.gnu.org/software/make/manual/html_node/Flavors.html I'd say maybe just keep using simply expanded variables for now and keep the specific behavior they have in mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by davidabrahams** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[Makefile, line 6 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SiGI_iJh7tbR9Q3NP:-L-Spp3gV0ur8gWreq-T:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/Makefile#L6)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

Gnu has a quick page on this, but it's still unclear which one we should use. https://www.gnu.org/software/make/manual/html_node/Flavors.html I'd say maybe just keep using simply expanded variables for now and keep the specific behavior they have in mind.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 5 at r6](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SofdRQlVA3rchIFqO:-L-Spx9dZ4JYbVb0U5D8:bqfbksc) ([raw file](https://github.com/shanek21/connect-four-ai/blob/4cf7c759a7546fb206174c7fbdb42843cb09b1d2/.travis.yml#L5)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

What's the difference? lol FYI, I was basing this on:

https://docs.travis-ci.com/user/installing-dependencies/
</blockquote></details>

```apt-get``` is being replaced with ```apt```, which, as far as I can tell, is a newer version of ```apt-get```. https://www.maketecheasier.com/apt-vs-apt-get-ubuntu/
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*
<!-- Sent from Reviewable.io -->

**Comment by williamalu** [comment]
Reviewed 2 of 3 files at r5, 1 of 2 files at r6.
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by davidabrahams** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 5 at r6](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SofdRQlVA3rchIFqO:-L-Su7-uXw2rUkSz8E6m:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/4cf7c759a7546fb206174c7fbdb42843cb09b1d2/.travis.yml#L5)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

```apt-get``` is being replaced with ```apt```, which, as far as I can tell, is a newer version of ```apt-get```. https://www.maketecheasier.com/apt-vs-apt-get-ubuntu/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Reviewed 3 of 3 files at r7.
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[Makefile, line 6 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SiGI_iJh7tbR9Q3NP:-L-SuYENauaoqa5H2KGX:b-mlqspx) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/Makefile#L6)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You actually switched away from simply expanded variables, but that's also ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by shanek21** [comment]
Reviewed 2 of 3 files at r5, 1 of 3 files at r7, 1 of 1 files at r8.
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 10 at r8](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-T0_HWmJuZm8L-n1Fj:-L-T0_HWmJuZm8L-n1Fk:b-ovwaw7) ([raw file](https://github.com/shanek21/connect-four-ai/blob/cbcb2a36654da0371421413331435123fa527dc6/.travis.yml#L10)):*
> ```YAML
> 
> script:
> - ./scripts/lint.sh
> ```

Good idea.

---

*[Makefile, line 6 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SiGI_iJh7tbR9Q3NP:-L-T0FNre-hhoomFLWir:b-6op4ed) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/Makefile#L6)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

You actually switched away from simply expanded variables, but that's also ok.
</blockquote></details>

If there's no difference to us, then I kind of like just the `=` sign!

---

*[scripts/lint.sh, line 8 at r8](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-T0SbavbDeuemJyEGU:-L-T0SbavbDeuemJyEGV:bgodqhm) ([raw file](https://github.com/shanek21/connect-four-ai/blob/cbcb2a36654da0371421413331435123fa527dc6/scripts/lint.sh#L8)):*
> ```Shell
> echo
> echo Running cppcheck...
> # cppcheck doesn't know about build in c++ libraries, this supresses warnings
> ```

Can you explain this comment? I think I'm confused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by shanek21** [comment]
Reviewed 1 of 3 files at r7.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by davidabrahams** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 6 at r4](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-SiGI_iJh7tbR9Q3NP:-L-T6KJVDANKrid3lzfT:b-r8p4ee) ([raw file](https://github.com/shanek21/connect-four-ai/blob/40c26c3d10f810a6c8802d81469cec554931aaa6/Makefile#L6)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

If there's no difference to us, then I kind of like just the `=` sign!
</blockquote></details>

plz set dispositions to okay

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by davidabrahams** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/lint.sh, line 8 at r8](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9#-L-T0SbavbDeuemJyEGU:-L-T6YJyBy_dIB8znwgZ:bao61g6) ([raw file](https://github.com/shanek21/connect-four-ai/blob/cbcb2a36654da0371421413331435123fa527dc6/scripts/lint.sh#L8)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you explain this comment? I think I'm confused.
</blockquote></details>

Oops, there was a typo. If you dont have this suppress thing here, you get:

```
Running cppcheck...
Checking src/connect_four.cpp...
(information) Cppcheck cannot find all the include files (use --check-config for details)
```

I think it's from `#include <iostream>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by williamalu** [comment]
Reviewed 1 of 1 files at r9.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r9.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/9)*

**Pull request merged**
