### PR TITLE
10 brute force test

### PR DESCRIPTION
**Pull request by davidabrahams**
This change is [Reviewable](https://reviewable.io/reviews/shanek21/connect-four-ai/18)

### CODE REVIEW

**Comment by williamalu** [comment]
Reviewed 3 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/state.h, line 76 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06mQmcnrnn2c5lns1F:-L06mQmcnrnn2c5lns1G:bzbe37d) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/include/state.h#L76)):*
> ```objc
> 
>   void placeTile(TileType color, int row, int col);
>   /* static State boardFromArray(char A[][]); */
> ```

What is this for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by williamalu** [comment]
Reviewed 2 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by williamalu** [comment]
Reviewed 2 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by williamalu** [comment]
Reviewed 1 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by davidabrahams** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/state.h, line 76 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06mQmcnrnn2c5lns1F:-L077I-oEMb9AYhTxB83:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/include/state.h#L76)):*
<details><summary><i>Previously, williamalu (William Lu) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by williamalu** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by shanek21** [comment]
Reviewed 8 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[Makefile, line 52 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06bEJKOqjtairgDUCU:-L06bEJLzFNwZIYRnLz8:bbvxoyl) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/Makefile#L52)):*
> ```Makefile
> 
> test: directories $(TEST_DIR)/state\
> 	$(TEST_DIR)/negamax
> ```

Delete newline escape

---

*[include/state.h, line 76 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06bPvBJBDdBR_Rl1ex:-L06bPvBJBDdBR_Rl1ey:b-7l6lmb) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/include/state.h#L76)):*
> ```objc
> 
>   void placeTile(TileType color, int row, int col);
>   /* static State boardFromArray(char A[][]); */
> ```

Are you saving this?

---

*[src/negamax.cpp, line 9 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06bbCVi-viOgM7Ixsi:-L06bbCWRsGC8ueuiTyY:b-lzroe9) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L9)):*
> ```cpp
>  *   if the next player to play will lose
>  */
> int negamax(const State S) {
> ```

Maybe don't capitalize the parameter `S`?

---

*[src/negamax.cpp, line 11 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06cSIWwcguuTQsVVQg:-L06cSIWwcguuTQsVVQh:bckh9h5) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L11)):*
> ```cpp
> int negamax(const State S) {
>   if (S.isBoardFull())  // if the game is over, it's a draw
>     return 0;
> ```

Make inline?

---

*[src/negamax.cpp, line 15 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06cC0Bxsyiu2VfwczU:-L06cC0Bxsyiu2VfwczV:b91bqmo) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L15)):*
> ```cpp
>   int width = State::WIDTH;
> 
>   for (int x = 0; x < width; x++) {
> ```

Replace `x` with `col`?

---

*[src/negamax.cpp, line 25 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L077HxwuhPQevAZkTGE:-L077Hxxl0ijqHQKGZYF:b91bqmo) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L25)):*
> ```cpp
>   int bestScore = -1;
> 
>   for (int x = 0; x < width; x++) {
> ```

Replace `x` with `col`?

---

*[src/negamax.cpp, line 33 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L077xJa35HKU2qVD_S7:-L077xJa35HKU2qVD_S8:bb7hc5e) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L33)):*
> ```cpp
>   }
>   return bestScore;
> }
> ```

halp

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by davidabrahams** [comment]
Review status: 6 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[Makefile, line 52 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06bEJKOqjtairgDUCU:-L0AVEjrfCg9LChPq1QV:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/Makefile#L52)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Delete newline escape
</blockquote></details>

Done.

---

*[include/state.h, line 76 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06bPvBJBDdBR_Rl1ex:-L0AVXkDieRZGjGVjehb:bn5buvl) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/include/state.h#L76)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Are you saving this?
</blockquote></details>

Done. Saved?

---

*[src/negamax.cpp, line 9 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06bbCVi-viOgM7Ixsi:-L0AVj26BsoPNAFR_K_f:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L9)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Maybe don't capitalize the parameter `S`?
</blockquote></details>

Done.

---

*[src/negamax.cpp, line 11 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06cSIWwcguuTQsVVQg:-L0AVsaguWvFaj4gjz77:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L11)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Make inline?
</blockquote></details>

Done.

---

*[src/negamax.cpp, line 15 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L06cC0Bxsyiu2VfwczU:-L0AVyxknypNI4hPL8YT:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L15)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Replace `x` with `col`?
</blockquote></details>

Done.

---

*[src/negamax.cpp, line 25 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L077HxwuhPQevAZkTGE:-L0AVznDBGA3OP6gmyWN:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L25)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Replace `x` with `col`?
</blockquote></details>

Done.

---

*[src/negamax.cpp, line 33 at r1](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-L077xJa35HKU2qVD_S7:-L0AWlh7hGqcRPh_qmEx:b-896fix) ([raw file](https://github.com/shanek21/connect-four-ai/blob/fd5bd19e66c7d4ac53ada5a2dd199515c9bb338d/src/negamax.cpp#L33)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

halp
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r3.
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18)*

**Comment by shanek21** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/18#-:-L0AgCJ63JVoS8wAupVz:bnfp4nl)*

**Pull request merged**
