### PR TITLE
2: add state class

### LINKED ISSUE #2: Create data structure for Connect Four board
A  class that:
  - Stores game state
  - Has a function that checks if a given game state results in a player winning
  - Has a function that makes moves, checks for move validity

### PR DESCRIPTION
**Pull request by shanek21**
Closes #2

---
This change is [Reviewable](https://reviewable.io/reviews/shanek21/connect-four-ai/16)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 3 of 11 files at r1, 2 of 7 files at r2, 5 of 5 files at r3.
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/state.cpp, line 11 at r3](https://reviewable.io:443/reviews/shanek21/connect-four-ai/16#-L06Ndmt5Bff8tulAjHI:-L06Ndmt5Bff8tulAjHJ:beeb5gw) ([raw file](https://github.com/shanek21/connect-four-ai/blob/e143ca53e14084a414a39225f797ae7e9dcb3481/src/state.cpp#L11)):*
> ```cpp
> }
> 
> State::State(const State* s) {
> ```

Do we have problems where the references exist in two diff objects (ie, we modify the bitboard in one State object, and it also changes in the other one?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/16)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r4.
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/16)*

**Comment by williamalu** [comment]
Reviewed 3 of 11 files at r1, 3 of 7 files at r2, 5 of 5 files at r3.
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/16)*

**Comment by williamalu** [comment]
Reviewed 1 of 1 files at r4.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shanek21/connect-four-ai/16)*

**Pull request merged**
